// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjgfwmfvsodpklnbqsxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZ2Z3bWZ2c29kcGtsbmJxc3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDA1MTYsImV4cCI6MjA2MzQ3NjUxNn0.VWA5oYP7OwWHAqQ6xbUNH07uhyEF8U640ui4W38TzO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);